FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["src/POS.WebAPI/POS.WebAPI.csproj", "src/POS.WebAPI/"]
COPY ["src/POS.Application/POS.Application.csproj", "src/POS.Application/"]
COPY ["src/POS.Domain/POS.Domain.csproj", "src/POS.Domain/"]
COPY ["src/POS.Infrastructure/POS.Infrastructure.csproj", "src/POS.Infrastructure/"]

RUN dotnet restore "src/POS.WebAPI/POS.WebAPI.csproj"

COPY . .
WORKDIR "/src/src/POS.WebAPI"
RUN dotnet build "POS.WebAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "POS.WebAPI.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "POS.WebAPI.dll"]
