apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netpos-ingress
  namespace: netpos
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - pos.yourdomain.com
      secretName: netpos-tls-secret
  rules:
    - host: pos.yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: netpos-api-service
                port:
                  number: 80
