
import { CrudDataTable } from '../components/CrudDataTable';
import type { ColumnDef, FormFieldDef } from '../components/CrudDataTable';

export function ReportsPage() {
  const columns: ColumnDef<any>[] = [
    { key: 'reportName', header: 'Report Name' },
    { key: 'generatedBy', header: 'Generated By' },
    { key: 'generatedAt', header: 'Generated At' }
  ];

  const formFields: FormFieldDef[] = [
    { name: 'reportName', label: 'Report Name', type: 'text', required: true },
    { name: 'generatedBy', label: 'Generated By', type: 'number', required: true },
    { name: 'generatedAt', label: 'Generated At', type: 'date', required: true },
    { name: 'content', label: 'Content', type: 'text' }
  ];

  return (
    <CrudDataTable 
      title="Reports"
      endpoint="/reports"
      columns={columns}
      formFields={formFields}
    />
  );
}
