import { useState, useEffect } from 'react';
import { CrudDataTable } from '../components/CrudDataTable';
import type { ColumnDef, FormFieldDef } from '../components/CrudDataTable';
import { fetchApi } from '../utils/api';

export function ReportsPage() {
  const [employees, setEmployees] = useState<{ id: number; firstName: string; lastName: string }[]>([]);

  useEffect(() => {
    fetchApi<{ data: { id: number; firstName: string; lastName: string }[] } | { id: number; firstName: string; lastName: string }[]>('/employees')
      .then(res => {
        if (res && typeof res === 'object' && 'data' in res && Array.isArray(res.data)) {
          setEmployees(res.data);
        } else if (Array.isArray(res)) {
          setEmployees(res);
        }
      })
      .catch(console.error);
  }, []);

  const columns: ColumnDef<any>[] = [
    { key: 'reportName', header: 'Report Name' },
    { 
      key: 'generatedBy', 
      header: 'Generated By',
      render: (row) => {
        const emp = employees.find(e => e.id === row.generatedBy);
        return emp ? `${emp.firstName} ${emp.lastName}` : row.generatedBy;
      }
    },
    { key: 'generatedAt', header: 'Generated At' }
  ];

  const formFields: FormFieldDef[] = [
    { name: 'reportName', label: 'Report Name', type: 'text', required: true },
    { 
      name: 'generatedBy', 
      label: 'Generated By', 
      type: 'select', 
      required: true,
      options: employees.map(e => ({ label: `${e.firstName} ${e.lastName}`, value: e.id }))
    },
    { name: 'generatedAt', label: 'Generated At', type: 'date', required: true },
    { name: 'content', label: 'Content', type: 'text' }
  ];

  return (
    <CrudDataTable 
      title="Reports"
      endpoint="/reports"
      columns={columns}
      formFields={formFields}
    />
  );
}
